### ISSUE TITLE
Discreapncy in the FR API Output and the FR link

### ISSUE THREAD

**Issue by Aniformer** [usnationalarchives/federalregister-api-core#23]
Hi team, 

This is to bring to your kind attention that recently while making a certain FR API call we noticed a discrepancy in the XML link returned by the API call and the FR link corresponding to the actual amendment/change. The FR API call made was as follows :- 

https://www.federalregister.gov/api/v1/documents/2020-01189.json. 
The corresponding API call's output is examined and the 'full_xml_text_url' field value is accessed and the corresponding FR URL is opened - https://www.federalregister.gov/documents/full_text/xml/2020/01/24/2020-01189.xml. 

Usually the XML file returned mimics the data represented on the actual FR link for this notification(https://www.federalregister.gov/documents/2019/11/14/2019-24366/us-citizenship-and-immigration-services-fee-schedule-and-changes-to-certain-other-immigration), but as observed under the 'List of Subjects' section of the FR link provided there is missing(incomplete) data from the XML file. 

We're trying to understand if this was caused by a mistake in the population of the XML document or is there a supplementary link/file/api output (json/xml) that we must look into to extract the required 'missing' information. 

Any clarity around this will be really helpful. 

Thank you, 
Anirudh

**Comment by andrewcarpenter** [comment]
Hi Anirudh,

I think the disconnect here is that there are two similar looking documents:

https://www.federalregister.gov/d/2019-24366
https://www.federalregister.gov/d/2020-01189

The JSON for the latter document references the full text XML for 2020-01189, which does not have a List of Subjects because document 2020-01189 is simply an extension of the comment period for 2019-24366. Does that make sense?

Thanks,

-Andrew
